/* Auto-generated by scripts/sync-public-images.ts — do not edit by hand. */
export type MediaLibraryItem = {
  id: string;
  label: string;
  group: string;
  localPath: string;
  url: string;
};

export const mediaLibrary: MediaLibraryItem[] = [
  {
    id: "amazon.svg",
    label: "Amazon",
    group: "Brand",
    localPath: "/images/amazon.svg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/amazon.svg",
  },
  {
    id: "icon.png",
    label: "Icon",
    group: "Brand",
    localPath: "/images/icon.png",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/icon.png",
  },
  {
    id: "icon.svg",
    label: "Icon",
    group: "Brand",
    localPath: "/images/icon.svg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/icon.svg",
  },
  {
    id: "logo.png",
    label: "Logo",
    group: "Brand",
    localPath: "/images/logo.png",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/logo.png",
  },
  {
    id: "logo-transparent.png",
    label: "Logo Transparent",
    group: "Brand",
    localPath: "/images/logo-transparent.png",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/logo-transparent.png",
  },
  {
    id: "generated/about.jpg",
    label: "About",
    group: "Generated",
    localPath: "/images/generated/about.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/about.jpg",
  },
  {
    id: "generated/care.jpg",
    label: "Care",
    group: "Generated",
    localPath: "/images/generated/care.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/care.jpg",
  },
  {
    id: "generated/diagnostics.jpg",
    label: "Diagnostics",
    group: "Generated",
    localPath: "/images/generated/diagnostics.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/diagnostics.jpg",
  },
  {
    id: "generated/exterior.jpg",
    label: "Exterior",
    group: "Generated",
    localPath: "/images/generated/exterior.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/exterior.jpg",
  },
  {
    id: "generated/hero.jpg",
    label: "Hero",
    group: "Generated",
    localPath: "/images/generated/hero.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/hero.jpg",
  },
  {
    id: "generated/hormone.jpg",
    label: "Hormone",
    group: "Generated",
    localPath: "/images/generated/hormone.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/hormone.jpg",
  },
  {
    id: "generated/iv.jpg",
    label: "Iv",
    group: "Generated",
    localPath: "/images/generated/iv.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/iv.jpg",
  },
  {
    id: "generated/nutrition.jpg",
    label: "Nutrition",
    group: "Generated",
    localPath: "/images/generated/nutrition.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/nutrition.jpg",
  },
  {
    id: "generated/pelvic.jpg",
    label: "Pelvic",
    group: "Generated",
    localPath: "/images/generated/pelvic.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/pelvic.jpg",
  },
  {
    id: "generated/reception.jpg",
    label: "Reception",
    group: "Generated",
    localPath: "/images/generated/reception.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/reception.jpg",
  },
  {
    id: "generated/skin.jpg",
    label: "Skin",
    group: "Generated",
    localPath: "/images/generated/skin.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/skin.jpg",
  },
  {
    id: "generated/supplements-hero.jpg",
    label: "Supplements Hero",
    group: "Generated",
    localPath: "/images/generated/supplements-hero.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/supplements-hero.jpg",
  },
  {
    id: "generated/weight.jpg",
    label: "Weight",
    group: "Generated",
    localPath: "/images/generated/weight.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/generated/weight.jpg",
  },
  {
    id: "staff/elina.jpg",
    label: "Elina",
    group: "Staff",
    localPath: "/images/staff/elina.jpg",
    url: "https://wrk6fbu5jhvrw06a.public.blob.vercel-storage.com/library/staff/elina.jpg",
  },
] as const;

export function mediaByLocalPath(localPath: string) {
  return mediaLibrary.find((item) => item.localPath === localPath);
}

export function mediaGroups() {
  return [...new Set(mediaLibrary.map((item) => item.group))];
}
