import { config } from "dotenv";
import { put } from "@vercel/blob";
import { eq } from "drizzle-orm";
import fs from "node:fs/promises";
import path from "node:path";

config({ path: ".env.local" });
config({ path: ".env" });

type MediaItem = {
  id: string;
  label: string;
  group: string;
  localPath: string;
  url: string;
};

const ROOT = path.join(process.cwd(), "public", "images");
const OUT_FILE = path.join(process.cwd(), "lib", "media-library.ts");

const SERVICE_IMAGE_MAP: Record<string, string> = {
  diagnostics: "generated/diagnostics.jpg",
  "iv-therapy": "generated/iv.jpg",
  "hormone-balancing": "generated/hormone.jpg",
  "weight-management": "generated/weight.jpg",
  "nutritional-analysis": "generated/nutrition.jpg",
  "pelvic-floor": "generated/pelvic.jpg",
  "skin-care": "generated/skin.jpg",
};

const CONTENT_TYPES: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".svg": "image/svg+xml",
};

async function walk(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (/\.(jpe?g|png|webp|svg)$/i.test(entry.name)) {
      files.push(full);
    }
  }
  return files;
}

function labelFromPath(rel: string) {
  const base = path.basename(rel, path.extname(rel));
  return base
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function groupFromPath(rel: string) {
  const parts = rel.split(/[\\/]/);
  if (parts.length === 1) return "Brand";
  return parts[0]
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

async function main() {
  if (!process.env.BLOB_READ_WRITE_TOKEN) {
    throw new Error("BLOB_READ_WRITE_TOKEN is required");
  }

  const files = await walk(ROOT);
  const library: MediaItem[] = [];

  for (const file of files) {
    const rel = path.relative(ROOT, file).replace(/\\/g, "/");
    const ext = path.extname(file).toLowerCase();
    const contentType = CONTENT_TYPES[ext] || "application/octet-stream";
    const bytes = await fs.readFile(file);
    const pathname = `library/${rel}`;

    console.log(`Uploading ${rel}...`);
    const blob = await put(pathname, bytes, {
      access: "public",
      contentType,
      addRandomSuffix: false,
      allowOverwrite: true,
    });

    library.push({
      id: rel,
      label: labelFromPath(rel),
      group: groupFromPath(rel),
      localPath: `/images/${rel}`,
      url: blob.url,
    });
  }

  library.sort((a, b) =>
    a.group === b.group
      ? a.label.localeCompare(b.label)
      : a.group.localeCompare(b.group),
  );

  const source = `/* Auto-generated by scripts/sync-public-images.ts — do not edit by hand. */
export type MediaLibraryItem = {
  id: string;
  label: string;
  group: string;
  localPath: string;
  url: string;
};

export const mediaLibrary: MediaLibraryItem[] = ${JSON.stringify(library, null, 2)} as const;

export function mediaByLocalPath(localPath: string) {
  return mediaLibrary.find((item) => item.localPath === localPath);
}

export function mediaGroups() {
  return [...new Set(mediaLibrary.map((item) => item.group))];
}
`;

  await fs.writeFile(OUT_FILE, source, "utf8");
  console.log(`Wrote ${library.length} items to lib/media-library.ts`);

  if (!process.env.DATABASE_URL) {
    console.warn("DATABASE_URL missing — skipped service image updates");
    return;
  }

  const { db } = await import("../lib/db");
  const { services } = await import("../lib/db/schema");

  for (const [slug, localRel] of Object.entries(SERVICE_IMAGE_MAP)) {
    const item = library.find((m) => m.id === localRel);
    if (!item) {
      console.warn(`No library image for ${slug} (${localRel})`);
      continue;
    }
    const existing = await db.query.services.findFirst({
      where: eq(services.slug, slug),
    });
    if (!existing) continue;
    await db
      .update(services)
      .set({ imageUrl: item.url, updatedAt: new Date() })
      .where(eq(services.id, existing.id));
    console.log(`Updated ${slug} → ${item.url}`);
  }

  console.log("Done.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
